// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Alpamys Kanibetov",
            "email": "alpamys.kanibetov@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/task": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/task/free_trash": {
            "delete": {
                "responses": {}
            }
        },
        "/task/status": {
            "get": {
                "responses": {}
            }
        },
        "/task/{id}": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/task/{id}/completely": {
            "delete": {
                "responses": {}
            }
        },
        "/task/{id}/done": {
            "put": {
                "responses": {}
            }
        },
        "/task/{id}/pause": {
            "put": {
                "responses": {}
            }
        },
        "/task/{id}/restore": {
            "put": {
                "responses": {}
            }
        },
        "/task/{id}/start_progress": {
            "put": {
                "responses": {}
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/rest",
	Schemes:          []string{},
	Title:            "Todo app API",
	Description:      "This is a sample todo app.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
