basePath: /rest
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: alpamys.kanibetov@gmail.com
    name: Alpamys Kanibetov
  description: This is a sample todo app.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Todo app API
  version: "1.0"
paths:
  /task:
    get:
      responses: {}
    post:
      responses: {}
  /task/{id}:
    delete:
      responses: {}
    get:
      responses: {}
    put:
      responses: {}
  /task/{id}/completely:
    delete:
      responses: {}
  /task/{id}/done:
    put:
      responses: {}
  /task/{id}/pause:
    put:
      responses: {}
  /task/{id}/restore:
    put:
      responses: {}
  /task/{id}/start_progress:
    put:
      responses: {}
  /task/free_trash:
    delete:
      responses: {}
  /task/status:
    get:
      responses: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
